name: Run Delivery Time Analysis

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or whichever version you require

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib seaborn

    - name: Run delivery time analysis
      run: |
        python delivery_time_analysis.py

    - name: List files in results directory
      run: |
        ls -al results/

    - name: Upload analysis results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: analysis-results
        path: results/
