name: Run Sortation Center Review

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 1 * * 1'  # Runs every Monday at 1:30 AM

jobs:
  sc-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib seaborn

    - name: Verify directory structure
      run: |
        echo "Listing root directory:" 
        ls -al /
        echo "Listing home directory:"
        ls -al ~/
        echo "Listing current directory:"
        ls -al

    - name: Run sortation center review
      run: |
        python sc_review.py

    - name: List files in output directory
      run: |
        ls -al output/

    - name: Upload analysis results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: sc-review-results
        path: output/
